name: "Snapcast Server"
version: "0.3.0"
slug: "snapcast_server"
description: "Snapcast server with Spotify connect support"
url: "https://github.com/developsad/hassio-addons/tree/master/snapcast"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
audio: true
map:
  - share:rw
options:
  spotify_name: "Home Assistant Sound System"
  spotify_username: ""
  spotify_password: ""
  log_level: "info"
schema:
  spotify_name: str
  spotify_username: str
  spotify_password: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
